### ISSUE TITLE
加入去精简分享后下载视频闪退 以下是崩溃日志

### ISSUE THREAD

**Issue by sjshb57** [Secack/ppx#21]
Process: com.sup.android.superb
PID: 28958
UID: 11025
Flags: 0x38d83e46
Package: com.sup.android.superb v410 (4.1.0)
Foreground: Yes
Process-Runtime: 47552197
Build: Redmi/lime/lime:12/SKQ1.211202.001/22.7.28:user/release-keys
Loading-Progress: 1.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sup.android.superb/com.sup.android.uikit.VideoDownloadProgressActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3774)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3941)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8312)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.addAll(ArrayList.java:588)
	at com.sup.android.m_sharecontroller.ui.g.a(SourceFile:91)
	at com.sup.android.m_sharecontroller.ui.g.setShareModel(SourceFile:65)
	at com.sup.android.m_sharecontroller.service.BaseShareService.getShareSimpleDialogView(SourceFile:641)
	at com.sup.android.uikit.VideoDownloadProgressActivity.onCreate(SourceFile:66)
	at android.app.Activity.performCreate(Activity.java:8192)
	at android.app.Activity.performCreate(Activity.java:8159)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1342)
	at com.bytedance.mira.hook.delegate.MiraInstrumentation.callActivityOnCreate(SourceFile:385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3754)
	... 12 more

**Comment by Secack** [comment]
已修复。
